version: "3.8"

services:
  php:
    container_name: savoirr_php
    build:
      context: php
    ports:
      - '9000:9000'
    volumes:
      - ./php:/var/www/php

  nginx:
    container_name: savoirr_nginx
    image: nginx:stable-alpine
    ports:
      - '8055:80'
    volumes:
      - ./php:/var/www/php
      - ./php/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php